"""empty message

Revision ID: 3916184b3a44
Revises: b031822e4be9
Create Date: 2018-12-08 17:47:20.098761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3916184b3a44'
down_revision = 'b031822e4be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'description')
    # ### end Alembic commands ###
